name: openmcyclus-env
channels:
  - conda-forge
  - defaults
dependencies:
  - gxx_linux-64=12.2 
  - gcc_linux-64=12.2 
  - cmake 
  - make 
  - hdf5=1.12.2 
  - notebook 
  - nb_conda_kernels 
  - requests 
  - entrypoints 
  - pyyaml 
  - vtk 
  - coverage 
  - pytest-cov 
  - colorama 
  - libpng 
  - uncertainties 
  - lxml 
  - scipy
