name: test-openmcyclus
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: openmcyclus-env
          environment-file: environment.yml
          use-mamba: true
          auto-activate-base: false

      - name: Conda config
        run: |
          conda config --env --set pip_interop_enabled True 
      
      - name: Update Environment
        run: |
          mamba env update -n openmcyclus-env -f environment.yml

      - name: Download Cyclus
        uses: actions/checkout@v3
        with:
          repository: abachma2/cyclus
          ref: python-api
          path: cyclus

      - name: Download Cycamore
        uses: actions/checkout@v3
        with:
            repository: abachma2/cycamore
            ref: 2023-04-maintenance
            path: cycamroe

      - name: Install Cyclus
        run: |
          cd cyclus
          python install.py
          cd ../

      - name: Install Cycamore
        run: |
            cd cycamore
            python install.py
            cd ../

      - name: Install OpenMC cross section library
        run: $GITHUB_WORKSPACE/openmc-xs.bash

      - name: Install OpenMC from Mamba
        run: mamba install openmc

      - name: Install OpenMC cross section library
        run: echo "OPENMC_CROSS_SECTIONS=cross_sections.xml" >> $GITHUB_ENV

      - name: Install OpenMCyclus
        run: |
          pip install .

      - name: Check environment
        run: |
          pip install pytest

      - name: Run Tests
        run: |
          pytest tests/integration_tests/test_depletereactor.py
