name: test-openmcyclus
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: openmcyclus-env
          environment-file: environment.yml
          auto-activate-base: false
          use-mamba: true          
        
      - name: Conda config
        run: |
          conda config --env --set pip_interop_enabled True 
      
      - name: Update Environment
        run: |
          mamba env update -n openmcyclus-env -f environment.yml

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          sudo apt -y update 
          sudo apt install -y libhdf5-dev
       
      - name: Install OpenMC
        run: mamba install openmc
#        run: $GITHUB_WORKSPACE/.github/workflows/build-openmc.sh

      - name: Install OpenMCyclus
        run: |
          pip install .
      
      - name: Find cross section data
      - run: |
          export $OPENMC_CROSS_SECTIONS=cross_sections.xml
          
      - name: Run Tests
      - run: |
          pytest
