version: 2.1

on:
  pull_request:
  workflow_run:
    workflows: []
    types: [completed]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - checkout
      - python/install-deps
      - run:
        name: Build Environment
        command: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            autoconf \
      
      - run:
        name: Build OpenMC
        command: |
          echo "Need to install OpenMC"

      - run:
        name: Run Tests
        command: |
          cd ~/project 
          pytest

workflows:
  version: 2.1
  main:
    jobs:
      - build-and-test