version: 2.1

name: test-openmcyclus
run-name: Creating Actions
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run:
        name: Build Environment
        command: |
          pip install -r requirements.txt
      
      - run:
        name: Build OpenMC
        command: |
          echo "Need to install OpenMC"

      - run:
        name: Install OpenMCyclus
        command: |
          pip install .

      - run:
        name: Run Tests
        command: |
          pytest